# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07834ac4f43c9ac3ccacc6ef7593a727440ab0eba3e886e742eefb74d50775ffd666e0fd242d9402766ea9a11b78503d6ce166d5bbee42725a9c320f268e55f9

test:
  secret_key_base: b5093157c85a9fbeaa845c97ea93557f6f07081d0ff39680512b0cf0e63ee42451ef39bd42749b6ea2c55834155bd0e0794a7967e8619136d4b9987c7d913400

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
